CREATE DATABASE IF NOT EXISTS `Posyandu Terpadu`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `Posyandu Terpadu`;

CREATE TABLE IF NOT EXISTS balita (
  id_balita INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  tanggal_lahir DATE NOT NULL,
  jenis_kelamin ENUM('L','P') NOT NULL,
  nama_ibu VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ibu_hamil (
  id_ibu INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  usia_kehamilan_minggu INT NOT NULL,
  alamat VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS imunisasi (
  id_imunisasi INT AUTO_INCREMENT PRIMARY KEY,
  id_balita INT NULL,
  nama_balita VARCHAR(100) NOT NULL,
  jenis_imunisasi VARCHAR(50) NOT NULL,
  tanggal DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_imunisasi_balita
    FOREIGN KEY (id_balita) REFERENCES balita(id_balita)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS pertumbuhan (
  id_pertumbuhan INT AUTO_INCREMENT PRIMARY KEY,
  id_balita INT NULL,
  nama_balita VARCHAR(100) NOT NULL,
  berat_kg DECIMAL(5,2) NOT NULL,
  tinggi_cm DECIMAL(5,2) NOT NULL,
  tanggal DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pertumbuhan_balita
    FOREIGN KEY (id_balita) REFERENCES balita(id_balita)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS jadwal (
  id_jadwal INT AUTO_INCREMENT PRIMARY KEY,
  tanggal DATE NOT NULL,
  tempat VARCHAR(150) NOT NULL,
  keterangan VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id_user INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nama_lengkap VARCHAR(100) NOT NULL,
  role ENUM('admin', 'petugas') NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (username, password_hash, nama_lengkap, role)
VALUES ('admin', '$2y$10$xdUefyiCnyr4npox.prkie6rJAsYPjaohUaHCWSTWiyRSbOT1DNdW', 'Administrator', 'admin')
ON DUPLICATE KEY UPDATE username = VALUES(username);
